name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: "latest"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Type Check
        run: pnpm run typeCheck

      - name: Build
        run: pnpm run build

      # - name: Test
      #   run: pnpm run test

      - name: Package
        run: pnpm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./a-soul-theme.vsix
